// data.js
const bigData = [
    {title:"Nebula OS Oficial", link:"https://miguel02714.github.io/nebula-os", desc:"O seu sistema operacional web acessível de qualquer lugar."},
    {title:"Documentação Nebula", link:"https://miguel02714.github.io/docs", desc:"Aprenda a usar todas as funcionalidades do Nebula OS."},
    {title:"Comunidade Nebula", link:"https://discord.gg/nebula", desc:"Conecte-se com outros usuários e desenvolvedores do Nebula OS."},
    {title:"Tutoriais", link:"https://miguel02714.github.io/tutorials", desc:"Tutoriais passo a passo para usar Nebula OS e apps."},
    {title:"Google", link:"https://www.google.com", desc:"O maior mecanismo de busca do mundo."},
    {title:"YouTube", link:"https://www.youtube.com", desc:"Plataforma de vídeos mais popular do mundo."},
    {title:"Facebook", link:"https://www.facebook.com", desc:"Rede social para conectar pessoas."},
    {title:"Instagram", link:"https://www.instagram.com", desc:"Compartilhe fotos e vídeos com amigos."},
    {title:"ChatGPT", link:"https://www.chatgpt.com", desc:"Inteligência artificial de conversação da OpenAI."},
    {title:"Wikipedia", link:"https://www.wikipedia.org", desc:"Enciclopédia livre e colaborativa."},
    {title:"Reddit", link:"https://www.reddit.com", desc:"Fóruns de discussão e notícias sociais."},
    {title:"X (Twitter)", link:"https://www.x.com", desc:"Rede social de microblogging."},
    {title:"WhatsApp", link:"https://www.whatsapp.com", desc:"Aplicativo de mensagens instantâneas."},
    {title:"Bing", link:"https://www.bing.com", desc:"Mecanismo de busca da Microsoft."},
    {title:"Yahoo!", link:"https://www.yahoo.com", desc:"Portal de notícias e e-mail."},
    {title:"Amazon", link:"https://www.amazon.com", desc:"E-commerce gigante mundial."},
    {title:"TikTok", link:"https://www.tiktok.com", desc:"Aplicativo de vídeos curtos e virais."},
    {title:"LinkedIn", link:"https://www.linkedin.com", desc:"Rede profissional para negócios e empregos."},
    {title:"Pinterest", link:"https://www.pinterest.com", desc:"Descubra ideias e inspirações visuais."},
    {title:"Baidu", link:"https://www.baidu.com", desc:"Principal mecanismo de busca da China."},
    {title:"Netflix", link:"https://www.netflix.com", desc:"Streaming de filmes e séries."},
    {title:"Yahoo! Japan", link:"https://www.yahoo.co.jp", desc:"Versão japonesa do portal Yahoo."},
    {title:"Yandex", link:"https://www.yandex.ru", desc:"Mecanismo de busca russo."},
    {title:"Twitch", link:"https://www.twitch.tv", desc:"Streaming de jogos e conteúdo ao vivo."},
    {title:"Microsoft", link:"https://www.microsoft.com", desc:"Software e tecnologia."},
    {title:"Live.com", link:"https://www.live.com", desc:"Serviços online da Microsoft."},
    {title:"Office", link:"https://www.office.com", desc:"Pacote de produtividade da Microsoft."},
    {title:"AliExpress", link:"https://www.aliexpress.com", desc:"Marketplace global da Alibaba."},
    {title:"Bilibili", link:"https://www.bilibili.com", desc:"Plataforma chinesa de vídeos."},
    {title:"Mail.ru", link:"https://www.mail.ru", desc:"Serviço de e-mail russo."},
    {title:"VK", link:"https://www.vk.com", desc:"Rede social russa."},
    {title:"Globo.com", link:"https://www.globo.com", desc:"Portal de notícias brasileiro."},
    {title:"Telegram", link:"https://t.me", desc:"Aplicativo de mensagens."},
    {title:"Canva", link:"https://www.canva.com", desc:"Ferramenta de design gráfico online."},
    {title:"DuckDuckGo", link:"https://www.duckduckgo.com", desc:"Mecanismo de busca focado na privacidade."},
    {title:"Booking.com", link:"https://www.booking.com", desc:"Plataforma de reservas de viagens."},
    {title:"eBay", link:"https://www.ebay.com", desc:"Marketplace global de compras e vendas."},
    {title:"New York Times", link:"https://www.nytimes.com", desc:"Jornal americano de notícias."},
    {title:"OpenAI", link:"https://www.openai.com", desc:"Pesquisa em inteligência artificial."},
    {title:"Spotify", link:"https://www.spotify.com", desc:"Serviço de streaming de música."},
    {title:"Trello", link:"https://www.trello.com", desc:"Ferramenta de gerenciamento de projetos."},
    {title:"Dropbox", link:"https://www.dropbox.com", desc:"Serviço de armazenamento em nuvem."},
    {title:"Quora", link:"https://www.quora.com", desc:"Plataforma de perguntas e respostas."},
    {title:"StackOverflow", link:"https://www.stackoverflow.com", desc:"Comunidade de desenvolvedores."},
    {title:"GitHub", link:"https://www.github.com", desc:"Plataforma de hospedagem de código."},
    {title:"Medium", link:"https://www.medium.com", desc:"Plataforma de blogs e artigos."},
    {title:"WhatsApp Web", link:"https://web.whatsapp.com", desc:"Versão web do WhatsApp."},
    {title:"Snapchat", link:"https://www.snapchat.com", desc:"Aplicativo de mensagens e mídias."},
    {title:"WeChat", link:"https://www.wechat.com", desc:"Aplicativo de mensagens chinês."},
    {title:"Skype", link:"https://www.skype.com", desc:"Serviço de chamadas de voz e vídeo."},
    {title:"Viber", link:"https://www.viber.com", desc:"Aplicativo de mensagens e chamadas."},
    {title:"Discord", link:"https://www.discord.com", desc:"Plataforma de comunicação para gamers."},
    {title:"Slack", link:"https://www.slack.com", desc:"Ferramenta de colaboração empresarial."},
    {title:"Zoom", link:"https://www.zoom.us", desc:"Plataforma de videoconferências."},
    {title:"Microsoft Teams", link:"https://www.microsoft.com/pt-br/microsoft-teams/group-chat-software", desc:"Ferramenta de colaboração da Microsoft."},
    {title:"Google Meet", link:"https://meet.google.com", desc:"Serviço de videoconferência do Google."},
    {title:"Jitsi Meet", link:"https://meet.jit.si", desc:"Plataforma de videoconferência de código aberto."},{title:"Google", link:"https://www.google.com", desc:"O maior mecanismo de busca do mundo."},
{title:"YouTube", link:"https://www.youtube.com", desc:"Plataforma de vídeos mais popular do mundo."},
{title:"Facebook", link:"https://www.facebook.com", desc:"Rede social para conectar pessoas."},
{title:"Instagram", link:"https://www.instagram.com", desc:"Compartilhe fotos e vídeos com amigos."},
{title:"ChatGPT", link:"https://www.chatgpt.com", desc:"Inteligência artificial de conversação da OpenAI."},
{title:"Wikipedia", link:"https://www.wikipedia.org", desc:"Enciclopédia livre e colaborativa."},
{title:"Reddit", link:"https://www.reddit.com", desc:"Fóruns de discussão e notícias sociais."},
{title:"X (Twitter)", link:"https://www.x.com", desc:"Rede social de microblogging."},
{title:"WhatsApp", link:"https://www.whatsapp.com", desc:"Aplicativo de mensagens instantâneas."},
{title:"Bing", link:"https://www.bing.com", desc:"Mecanismo de busca da Microsoft."},
{title:"Yahoo!", link:"https://www.yahoo.com", desc:"Portal de notícias e e-mail."},
{title:"Amazon", link:"https://www.amazon.com", desc:"E-commerce gigante mundial."},
{title:"TikTok", link:"https://www.tiktok.com", desc:"Aplicativo de vídeos curtos e virais."},
{title:"LinkedIn", link:"https://www.linkedin.com", desc:"Rede profissional para negócios e empregos."},
{title:"Pinterest", link:"https://www.pinterest.com", desc:"Descubra ideias e inspirações visuais."},
{title:"Baidu", link:"https://www.baidu.com", desc:"Principal mecanismo de busca da China."},
{title:"Netflix", link:"https://www.netflix.com", desc:"Streaming de filmes e séries."},
{title:"Yahoo! Japan", link:"https://www.yahoo.co.jp", desc:"Versão japonesa do portal Yahoo."},
{title:"Yandex", link:"https://www.yandex.ru", desc:"Mecanismo de busca russo."},
{title:"Twitch", link:"https://www.twitch.tv", desc:"Streaming de jogos e conteúdo ao vivo."},
{title:"Microsoft", link:"https://www.microsoft.com", desc:"Software e tecnologia."},
{title:"Live.com", link:"https://www.live.com", desc:"Serviços online da Microsoft."},
{title:"Office", link:"https://www.office.com", desc:"Pacote de produtividade da Microsoft."},
{title:"AliExpress", link:"https://www.aliexpress.com", desc:"Marketplace global da Alibaba."},
{title:"Bilibili", link:"https://www.bilibili.com", desc:"Plataforma chinesa de vídeos."},
{title:"Mail.ru", link:"https://www.mail.ru", desc:"Serviço de e-mail russo."},
{title:"VK", link:"https://www.vk.com", desc:"Rede social russa."},
{title:"Globo.com", link:"https://www.globo.com", desc:"Portal de notícias brasileiro."},
{title:"Telegram", link:"https://t.me", desc:"Aplicativo de mensagens."},
{title:"Canva", link:"https://www.canva.com", desc:"Ferramenta de design gráfico online."},
{title:"DuckDuckGo", link:"https://www.duckduckgo.com", desc:"Mecanismo de busca focado na privacidade."},
{title:"Booking.com", link:"https://www.booking.com", desc:"Plataforma de reservas de viagens."},
{title:"eBay", link:"https://www.ebay.com", desc:"Marketplace global de compras e vendas."},
{title:"New York Times", link:"https://www.nytimes.com", desc:"Jornal americano de notícias."},
{title:"OpenAI", link:"https://www.openai.com", desc:"Pesquisa em inteligência artificial."},
{title:"Spotify", link:"https://www.spotify.com", desc:"Serviço de streaming de música."},
{title:"Trello", link:"https://www.trello.com", desc:"Ferramenta de gerenciamento de projetos."},
{title:"Dropbox", link:"https://www.dropbox.com", desc:"Serviço de armazenamento em nuvem."},
{title:"Quora", link:"https://www.quora.com", desc:"Plataforma de perguntas e respostas."},
{title:"StackOverflow", link:"https://www.stackoverflow.com", desc:"Comunidade de desenvolvedores."},
{title:"GitHub", link:"https://www.github.com", desc:"Plataforma de hospedagem de código."},
{title:"Medium", link:"https://www.medium.com", desc:"Plataforma de blogs e artigos."},
{title:"WhatsApp Web", link:"https://web.whatsapp.com", desc:"Versão web do WhatsApp."},
{title:"Snapchat", link:"https://www.snapchat.com", desc:"Aplicativo de mensagens e mídias."},
{title:"Skype", link:"https://www.skype.com", desc:"Serviço de chamadas de voz e vídeo."},
{title:"Viber", link:"https://www.viber.com", desc:"Aplicativo de mensagens e chamadas."},
{title:"Discord", link:"https://www.discord.com", desc:"Plataforma de comunicação para gamers."},
{title:"Slack", link:"https://www.slack.com", desc:"Ferramenta de colaboração empresarial."},
{title:"Zoom", link:"https://www.zoom.us", desc:"Plataforma de videoconferências."},
{title:"Microsoft Teams", link:"https://www.microsoft.com/pt-br/microsoft-teams/group-chat-software", desc:"Ferramenta de colaboração da Microsoft."},
{title:"Google Meet", link:"https://meet.google.com", desc:"Serviço de videoconferência do Google."},
{title:"Jitsi Meet", link:"https://meet.jit.si", desc:"Plataforma de videoconferência de código aberto."},
{title:"Reddit", link:"https://www.reddit.com", desc:"Fóruns de discussão e notícias sociais."},
{title:"StackOverflow", link:"https://www.stackoverflow.com", desc:"Comunidade de desenvolvedores."},
{title:"GitHub", link:"https://www.github.com", desc:"Plataforma de hospedagem de código."},
{title:"Medium", link:"https://www.medium.com", desc:"Plataforma de blogs e artigos."},
{title:"WhatsApp Web", link:"https://web.whatsapp.com", desc:"Versão web do WhatsApp."},
{title:"TikTok", link:"https://www.tiktok.com", desc:"Aplicativo de vídeos curtos e virais."},
{title:"Pinterest", link:"https://www.pinterest.com", desc:"Descubra ideias e inspirações visuais."},
{title:"Netflix", link:"https://www.netflix.com", desc:"Streaming de filmes e séries."},
{title:"YouTube", link:"https://www.youtube.com", desc:"Plataforma de vídeos mais popular do mundo."},
{title:"Facebook", link:"https://www.facebook.com", desc:"Rede social para conectar pessoas."},
{title:"Instagram", link:"https://www.instagram.com", desc:"Compartilhe fotos e vídeos com amigos."},
{title:"Snapchat", link:"https://www.snapchat.com", desc:"Aplicativo de mensagens e mídias."},
{title:"Telegram", link:"https://t.me", desc:"Aplicativo de mensagens."},
{title:"LinkedIn", link:"https://www.linkedin.com", desc:"Rede profissional para negócios e empregos."},
{title:"Reddit", link:"https://www.reddit.com", desc:"Fóruns de discussão e notícias sociais."},
{title:"Pinterest", link:"https://www.pinterest.com", desc:"Descubra ideias e inspirações visuais."},
{title:"WhatsApp", link:"https://www.whatsapp.com", desc:"Aplicativo de mensagens instantâneas."},
{title:"WeChat", link:"https://www.wechat.com", desc:"Aplicativo de mensagens chinês."},
{title:"Skype", link:"https://www.skype.com", desc:"Serviço de chamadas de voz e vídeo."},
{title:"Viber", link:"https://www.viber.com", desc:"Aplicativo de mensagens e chamadas."},
{title:"Discord", link:"https://www.discord.com", desc:"Plataforma de comunicação para gamers."},
{title:"Slack", link:"https://www.slack.com", desc:"Ferramenta de colaboração empresarial."},
{title:"Zoom", link:"https://www.zoom.us", desc:"Plataforma de videoconferências."},
{title:"Microsoft Teams", link:"https://www.microsoft.com/pt-br/microsoft-teams/group-chat-software", desc:"Ferramenta de colaboração da Microsoft."},
{title:"Google Meet", link:"https://meet.google.com", desc:"Serviço de videoconferência do Google."},
{title:"Jitsi Meet", link:"https://meet.jit.si", desc:"Plataforma de videoconferência de código aberto."},
{title:"Reddit", link:"https://www.reddit.com", desc:"Fóruns de discussão e notícias sociais."},
{title:"StackOverflow", link:"https://www.stackoverflow.com", desc:"Comunidade de desenvolvedores."},
{title:"GitHub", link:"https://www.github.com", desc:"Plataforma de hospedagem de código."},
{title:"Medium", link:"https://www.medium.com", desc:"Plataforma de blogs e artigos."},
{title:"WhatsApp Web", link:"https://web.whatsapp.com", desc:"Versão web do WhatsApp."},
{title:"TikTok", link:"https://www.tiktok.com", desc:"Aplicativo de vídeos curtos e virais."},
{title:"Pinterest", link:"https://www.pinterest.com", desc:"Descubra ideias e inspirações visuais."},
{title:"Netflix", link:"https://www.netflix.com", desc:"Streaming de filmes e séries."},
{title:"YouTube", link:"https://www.youtube.com", desc:"Plataforma de vídeos mais popular do mundo."},
{title:"Facebook", link:"https://www.facebook.com", desc:"Rede social para conectar pessoas."},

];
